### ISSUE TITLE
Error with make command

### ISSUE THREAD

**Issue by PawelGluszek** [lhark/truckersmp-cli#107]
How can i fix this error when typing make `make` in truckersmp files directory?

`make
if command -v genzshcomp > /dev/null; then \
	./truckersmp-cli --help | genzshcomp -f zsh > _truckersmp-cli; \
fi
if command -v genzshcomp > /dev/null; then \
	./truckersmp-cli --help | genzshcomp -f bash > truckersmp-cli.bash; \
fi`

**Comment by Lucki** [comment]
I don't see an error, did you copy the whole output?

Make sure you're following the [build steps](https://github.com/lhark/truckersmp-cli/blob/master/README.md#build) and have the [dependencies](https://github.com/lhark/truckersmp-cli/blob/master/README.md#buildtime-dependencies) available.

**Comment by PawelGluszek** [comment]
now i'm trying to run truckersmp-cli and i get this

`pawel@pawel-desktop:~/.local/share/Steam/steamapps/common/Euro Truck Simulator 2/truckersmp-cli$ truckersmp-cli
Traceback (most recent call last):
  File "/usr/local/bin/truckersmp-cli", line 4, in <module>
    __import__('pkg_resources').run_script('truckersmp-cli==0.1.0', 'truckersmp-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/truckersmp_cli-0.1.0-py2.7.egg/EGG-INFO/scripts/truckersmp-cli", line 11, in <module>
    from truckersmp_cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/truckersmp_cli-0.1.0-py2.7.egg/truckersmp_cli/main.py", line 15, in <module>
    from .args import check_args_errors, create_arg_parser
  File "/usr/local/lib/python2.7/dist-packages/truckersmp_cli-0.1.0-py2.7.egg/truckersmp_cli/args.py", line 13, in <module>
    from .utils import VDF_IS_AVAILABLE, get_current_steam_user
  File "/usr/local/lib/python2.7/dist-packages/truckersmp_cli-0.1.0-py2.7.egg/truckersmp_cli/utils.py", line 216
    print("\r{:40}{:>40}".format(name_getting, progress), end="")
                                                             ^
SyntaxError: invalid syntax
`

**Comment by Lucki** [comment]
> python2.7

Please make sure your [dependencies](https://github.com/lhark/truckersmp-cli#runtime-dependencies) are up to date.

**Comment by PawelGluszek** [comment]
What should I do with this output?

`sudo truckersmp-cli -n niecierpliwiec
Failed to get Wine process list: `

**Comment by Lucki** [comment]
Don't use sudo.

However, since your initial problem seems to be resolved I'm closing this one.
If you have further problems please open a new issue and make sure you're using the provided issue template this time.
